# Версия синтаксиса Docker Compose. Используем 3.8 как актуальную.
version: '3.8'

services:
  # Наш единственный сервис, который мы назовем 'web'.
  web:
    # Docker будет использовать Dockerfile в текущей директории для сборки образа.
    build: .

    # Связываем порт 80 контейнера с портом 80 на вашей машине.
    # Так вы сможете открыть сайт по адресу http://localhost.
    ports:
      - "80:80"

    # Подключаем локальную папку с проектом к папке внутри контейнера.
    # Это ключевой момент!
    # - "./": указывает на текущую директорию на вашей машине.
    # - "/var/www/html": указывает на рабочую директорию внутри контейнера.
    # Благодаря этому, вам не нужно пересобирать образ после каждого 'npm run build'.
    # Изменения в вашей локальной папке 'build' будут мгновенно видны в контейнере.
    volumes:
      - .:/var/www/html

    # Перезапускать контейнер автоматически в случае сбоя.
    restart: always
